import type { Categoria } from "./tipos";

/**
 * Dicionário de competências usado para ler a vaga sem IA.
 * Cada entrada: termo canônico, categoria, variantes com o MESMO significado
 * e, opcionalmente, `generico: true` para termos que só contam quando a vaga
 * os repete (ex.: "proatividade", "trabalho em equipe").
 */
export interface EntradaDicionario {
  termo: string;
  categoria: Categoria;
  variantes: string[];
  generico?: boolean;
}

type Linha = [termo: string, variantes?: string[], generico?: boolean];

function grupo(categoria: Categoria, linhas: Linha[]): EntradaDicionario[] {
  return linhas.map(([termo, variantes = [], generico]) => ({ termo, categoria, variantes, generico }));
}

const FERRAMENTAS = grupo("ferramenta", [
  // Programação e dados
  ["Python"],
  ["Java"],
  ["JavaScript", ["js", "ecmascript"]],
  ["TypeScript", ["ts"]],
  ["Node.js", ["nodejs", "node"]],
  ["React", ["react.js", "reactjs"]],
  ["React Native"],
  ["Next.js", ["nextjs"]],
  ["Angular", ["angularjs"]],
  ["Vue.js", ["vue", "vuejs"]],
  ["HTML", ["html5"]],
  ["CSS", ["css3"]],
  ["Tailwind CSS", ["tailwind"]],
  ["Sass", ["scss"]],
  ["PHP"],
  ["Laravel"],
  ["Ruby"],
  ["Ruby on Rails", ["rails"]],
  ["C#", ["csharp"]],
  ["C++"],
  [".NET", ["dotnet", "asp.net", ".net core"]],
  ["Golang", ["go lang"]],
  ["Kotlin"],
  ["Swift"],
  ["Flutter"],
  ["Dart"],
  ["Spring Boot", ["spring"]],
  ["Django"],
  ["Flask"],
  ["FastAPI"],
  ["GraphQL"],
  ["SQL"],
  ["MySQL"],
  ["PostgreSQL", ["postgres"]],
  ["SQL Server", ["mssql"]],
  ["Oracle"],
  ["MongoDB", ["mongo"]],
  ["Redis"],
  ["Elasticsearch"],
  ["Git"],
  ["GitHub"],
  ["GitLab"],
  ["Docker"],
  ["Kubernetes", ["k8s"]],
  ["Terraform"],
  ["AWS", ["amazon web services"]],
  ["Azure", ["microsoft azure"]],
  ["Google Cloud", ["gcp", "google cloud platform"]],
  ["Linux"],
  ["Windows Server"],
  ["Jenkins"],
  ["Selenium"],
  ["Cypress"],
  ["Jest"],
  ["Postman"],
  ["Pandas"],
  ["NumPy"],
  ["Spark", ["apache spark", "pyspark"]],
  ["Airflow", ["apache airflow"]],
  ["Databricks"],
  ["Snowflake"],
  ["Power BI", ["powerbi"]],
  ["Tableau"],
  ["Looker"],
  ["Qlik", ["qlik sense", "qlikview"]],
  ["Metabase"],
  ["Excel", ["ms excel", "microsoft excel"]],
  ["VBA", ["macros em vba"]],
  ["Pacote Office", ["microsoft office", "ms office", "office 365", "microsoft 365"]],
  ["Google Workspace", ["g suite", "gsuite"]],
  ["Google Sheets", ["planilhas google"]],
  // Gestão, vendas e marketing
  ["Jira"],
  ["Confluence"],
  ["Trello"],
  ["Notion"],
  ["Asana"],
  ["Monday", ["monday.com"]],
  ["Salesforce"],
  ["HubSpot"],
  ["Pipedrive"],
  ["RD Station"],
  ["Zendesk"],
  ["Google Analytics", ["ga4"]],
  ["Google Tag Manager", ["gtm"]],
  ["Google Ads", ["adwords", "google adwords"]],
  ["Meta Ads", ["facebook ads", "instagram ads"]],
  ["LinkedIn Ads"],
  ["SEMrush"],
  ["WordPress"],
  ["Shopify"],
  ["VTEX"],
  ["CRM"],
  ["ERP"],
  ["SAP"],
  ["TOTVS"],
  ["Protheus"],
  ["Senior Sistemas"],
  ["Oracle NetSuite", ["netsuite"]],
  ["Omie"],
  ["Conta Azul"],
  ["Domínio Sistemas", ["dominio contabil"]],
  // Design
  ["Figma"],
  ["Adobe Photoshop", ["photoshop"]],
  ["Adobe Illustrator", ["illustrator"]],
  ["Adobe InDesign", ["indesign"]],
  ["Adobe Premiere", ["premiere"]],
  ["After Effects"],
  ["Canva"],
  ["Adobe XD"],
  // Engenharia e indústria
  ["AutoCAD"],
  ["Revit"],
  ["SolidWorks"],
  ["SketchUp"],
  ["MS Project", ["microsoft project"]],
  ["Minitab"],
  ["CLP", ["controlador lógico programável"]],
]);

const TECNICAS = grupo("tecnica", [
  // Tecnologia
  ["APIs REST", ["api rest", "rest api", "apis restful", "restful", "api restful"]],
  ["Microsserviços", ["microservices", "microsserviço", "microserviços"]],
  ["CI/CD", ["integração contínua", "entrega contínua"]],
  ["DevOps"],
  ["Cloud", ["computação em nuvem"]],
  ["Testes automatizados", ["automação de testes", "testes automáticos"]],
  ["Testes unitários", ["unit tests", "testes de unidade"]],
  ["TDD"],
  ["Clean Code", ["código limpo"]],
  ["Arquitetura de software"],
  ["Orientação a objetos", ["programação orientada a objetos", "poo"]],
  ["Front-end", ["frontend"]],
  ["Back-end", ["backend"]],
  ["Full stack", ["fullstack"]],
  ["Mobile", ["desenvolvimento mobile"]],
  ["Segurança da informação", ["cibersegurança", "cybersecurity"]],
  ["Infraestrutura de TI", ["infraestrutura"]],
  ["Redes de computadores"],
  ["Suporte técnico", ["help desk", "service desk"]],
  ["Banco de dados", ["bancos de dados"]],
  ["Modelagem de dados"],
  ["Engenharia de dados"],
  ["ETL"],
  ["Data Warehouse", ["dw"]],
  ["Big Data"],
  ["Análise de dados", ["análises de dados", "data analysis"]],
  ["Ciência de dados", ["data science"]],
  ["Machine Learning", ["aprendizado de máquina"]],
  ["Inteligência artificial"],
  ["Estatística"],
  ["Business Intelligence", ["bi"]],
  ["Dashboards", ["dashboard", "painéis gerenciais"]],
  ["UX", ["user experience", "experiência do usuário", "ux design"]],
  ["UI", ["ui design", "interface do usuário"]],
  ["Design System"],
  ["Pesquisa com usuários", ["user research", "pesquisa de usuários"]],
  ["Prototipação", ["protótipos", "prototipagem"]],
  ["Design gráfico"],
  ["Edição de vídeo"],
  // Gestão e processos
  ["Gestão de projetos", ["gerenciamento de projetos", "gerência de projetos"]],
  ["Metodologias ágeis", ["métodos ágeis", "agile", "metodologia ágil"]],
  ["Scrum"],
  ["Kanban"],
  ["Lean", ["lean manufacturing"]],
  ["Six Sigma", ["seis sigma", "lean six sigma"]],
  ["Melhoria contínua", ["kaizen"]],
  ["Mapeamento de processos", ["modelagem de processos", "bpm"]],
  ["Gestão de processos"],
  ["KPIs", ["kpi", "indicadores de desempenho", "indicadores de performance"]],
  ["OKRs", ["okr"]],
  ["Planejamento estratégico"],
  ["Gestão de equipes", ["gestão de times", "liderança de equipes", "liderança de times"]],
  ["Gestão de pessoas"],
  ["Gestão de contratos"],
  ["Gestão de fornecedores"],
  ["Gestão de stakeholders", ["relacionamento com stakeholders", "comunicação com stakeholders"]],
  ["Product Management", ["gestão de produtos", "gestão de produto"]],
  ["Roadmap"],
  ["Discovery", ["product discovery"]],
  // Finanças, contabilidade e administrativo
  ["Contabilidade", ["contábil"]],
  ["Contas a pagar"],
  ["Contas a receber"],
  ["Conciliação bancária"],
  ["Fluxo de caixa"],
  ["Faturamento"],
  ["Cobrança"],
  ["Tesouraria"],
  ["Controladoria"],
  ["Auditoria"],
  ["Orçamento", ["budget", "orçamento empresarial"]],
  ["Planejamento financeiro"],
  ["Análise financeira"],
  ["Modelagem financeira"],
  ["Valuation"],
  ["Custos", ["gestão de custos", "análise de custos"]],
  ["DRE", ["demonstração do resultado"]],
  ["Balanço patrimonial"],
  ["Fechamento contábil"],
  ["Rotinas fiscais", ["escrita fiscal"]],
  ["Apuração de impostos", ["apuração de tributos"]],
  ["SPED"],
  ["IFRS"],
  ["Compliance"],
  ["Gestão de riscos"],
  ["Rotinas administrativas"],
  ["Emissão de notas fiscais", ["emissão de nf", "emissão de nota fiscal"]],
  // RH
  ["Recrutamento e seleção"],
  ["Departamento pessoal"],
  ["Folha de pagamento"],
  ["Admissão e demissão", ["admissões e demissões"]],
  ["eSocial"],
  ["Legislação trabalhista"],
  ["Treinamento e desenvolvimento"],
  ["Avaliação de desempenho"],
  ["Cargos e salários"],
  ["Clima organizacional"],
  ["Endomarketing"],
  ["Business Partner", ["hrbp"]],
  // Comercial e marketing
  ["Vendas"],
  ["Vendas consultivas", ["venda consultiva"]],
  ["Vendas B2B", ["b2b"]],
  ["Vendas B2C", ["b2c"]],
  ["Prospecção", ["prospecção de clientes", "prospecção ativa"]],
  ["Negociação"],
  ["Pós-venda"],
  ["Atendimento ao cliente"],
  ["Customer Success", ["sucesso do cliente"]],
  ["Telemarketing"],
  ["Inside Sales"],
  ["Funil de vendas", ["pipeline de vendas"]],
  ["Metas comerciais", ["metas de vendas"]],
  ["Marketing digital"],
  ["Inbound marketing"],
  ["Marketing de conteúdo"],
  ["Mídias sociais", ["redes sociais", "social media"]],
  ["SEO"],
  ["SEM"],
  ["Mídia paga", ["tráfego pago"]],
  ["E-mail marketing"],
  ["Copywriting", ["redação publicitária"]],
  ["Branding"],
  ["Growth", ["growth marketing", "growth hacking"]],
  ["E-commerce", ["ecommerce", "comércio eletrônico"]],
  ["Trade marketing"],
  ["Pesquisa de mercado"],
  // Logística, indústria e engenharia
  ["Logística"],
  ["Supply chain", ["cadeia de suprimentos"]],
  ["Gestão de estoque", ["controle de estoque"]],
  ["Compras", ["suprimentos"]],
  ["Almoxarifado"],
  ["Expedição"],
  ["Roteirização"],
  ["PCP", ["planejamento e controle da produção"]],
  ["Manutenção preventiva"],
  ["Manutenção corretiva"],
  ["Manutenção preditiva"],
  ["PCM", ["planejamento e controle da manutenção"]],
  ["Controle de qualidade"],
  ["5S"],
  ["FMEA"],
  ["Leitura de desenho técnico", ["desenho técnico"]],
  ["Elétrica", ["elétrica industrial"]],
  ["Mecânica"],
  ["Automação industrial"],
  ["Segurança do trabalho"],
  ["Operação de empilhadeira", ["empilhadeira"]],
  ["BIM"],
  ["Orçamento de obras"],
  // Saúde, jurídico e educação
  ["Enfermagem"],
  ["Primeiros socorros"],
  ["Atendimento humanizado"],
  ["Farmácia"],
  ["Prontuário eletrônico"],
  ["Direito trabalhista"],
  ["Direito tributário"],
  ["Direito civil"],
  ["Contencioso"],
  ["Elaboração de contratos", ["redação de contratos"]],
  ["LGPD", ["lei geral de proteção de dados"]],
  ["Docência"],
  ["Planejamento de aulas", ["planejamento pedagógico"]],
  ["Educação infantil"],
  ["Ensino a distância", ["ead"]],
]);

const COMPORTAMENTAIS = grupo("comportamental", [
  ["Liderança"],
  ["Resolução de problemas", ["solução de problemas"]],
  ["Pensamento analítico", ["raciocínio analítico", "perfil analítico", "visão analítica"]],
  ["Pensamento crítico"],
  ["Visão sistêmica"],
  ["Tomada de decisão"],
  ["Foco em resultados", ["orientação a resultados", "orientado a resultados", "orientada a resultados"]],
  ["Gestão do tempo"],
  ["Inteligência emocional"],
  ["Oratória", ["apresentações em público"]],
  ["Comunicação", ["boa comunicação"], true],
  ["Trabalho em equipe", ["espírito de equipe"], true],
  ["Proatividade", ["proativo", "proativa"], true],
  ["Senso de organização", ["organizado", "organizada"], true],
  ["Flexibilidade", ["flexível"], true],
  ["Criatividade", ["criativo", "criativa"], true],
  ["Empatia", [], true],
  ["Autonomia", [], true],
  ["Senso de urgência"],
  ["Relacionamento interpessoal"],
  ["Adaptabilidade"],
  ["Atenção aos detalhes"],
]);

const CERTIFICACOES_IDIOMAS = grupo("certificacao_idioma", [
  ["Inglês", ["english"]],
  ["Espanhol", ["spanish"]],
  ["Francês"],
  ["Alemão"],
  ["Italiano"],
  ["Mandarim"],
  ["Libras"],
  ["PMP"],
  ["Scrum Master", ["csm", "psm"]],
  ["ITIL"],
  ["CPA-10"],
  ["CPA-20"],
  ["CEA"],
  ["CFP"],
  ["CNPI"],
  ["CRC"],
  ["OAB"],
  ["CREA"],
  ["COREN"],
  ["CRP"],
  ["CNH", ["carteira de habilitação", "carteira nacional de habilitação"]],
  ["NR-10", ["nr10"]],
  ["NR-12", ["nr12"]],
  ["NR-35", ["nr35"]],
  ["NR-33", ["nr33"]],
  ["ISO 9001"],
  ["ISO 27001"],
  ["ISO 14001"],
  ["AWS Certified", ["certificação aws"]],
  ["Azure Fundamentals", ["az-900"]],
  ["Ensino superior completo", ["superior completo", "graduação completa"]],
  ["Pós-graduação", ["pós graduação", "especialização"]],
  ["MBA"],
  ["Mestrado"],
]);

export const DICIONARIO: EntradaDicionario[] = [
  ...FERRAMENTAS,
  ...TECNICAS,
  ...COMPORTAMENTAIS,
  ...CERTIFICACOES_IDIOMAS,
];
